spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bokyak_database?serverTimezone=Asia/Seoul
    username: bokyak
    password: bokyakPwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: classpath:jwt.yml

  # 콘솔 색상 출력
  output:
    ansi:
      enabled: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI URL
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서 URL